// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cluster/proto/subscriptions/subscriptions.proto

/*
Package subscriptions is a generated protocol buffer package.

It is generated from these files:
	api/cluster/proto/subscriptions/subscriptions.proto

It has these top-level messages:
	SubscriptionsReq
	SubscriptionsResp
	Subscriptition
*/
package subscriptions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import clients "github.com/hb-go/micro-mq/api/cluster/proto/clients"
import topics "github.com/hb-go/micro-mq/api/cluster/proto/topics"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubscriptionsReq struct {
	Page int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *SubscriptionsReq) Reset()                    { *m = SubscriptionsReq{} }
func (m *SubscriptionsReq) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsReq) ProtoMessage()               {}
func (*SubscriptionsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SubscriptionsReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SubscriptionsReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SubscriptionsResp struct {
	Subscriptions []*Subscriptition `protobuf:"bytes,1,rep,name=subscriptions" json:"subscriptions,omitempty"`
}

func (m *SubscriptionsResp) Reset()                    { *m = SubscriptionsResp{} }
func (m *SubscriptionsResp) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsResp) ProtoMessage()               {}
func (*SubscriptionsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscriptionsResp) GetSubscriptions() []*Subscriptition {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type Subscriptition struct {
	Client *clients.Client `protobuf:"bytes,1,opt,name=client" json:"client,omitempty"`
	Topic  *topics.Topic   `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
}

func (m *Subscriptition) Reset()                    { *m = Subscriptition{} }
func (m *Subscriptition) String() string            { return proto.CompactTextString(m) }
func (*Subscriptition) ProtoMessage()               {}
func (*Subscriptition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Subscriptition) GetClient() *clients.Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Subscriptition) GetTopic() *topics.Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscriptionsReq)(nil), "subscriptions.SubscriptionsReq")
	proto.RegisterType((*SubscriptionsResp)(nil), "subscriptions.SubscriptionsResp")
	proto.RegisterType((*Subscriptition)(nil), "subscriptions.Subscriptition")
}

func init() {
	proto.RegisterFile("api/cluster/proto/subscriptions/subscriptions.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0x28, 0x74, 0xb8, 0xa8, 0x7c, 0x78, 0x8a, 0x2a, 0x21, 0x55, 0x61, 0xa0, 0x4b, 0x6d,
	0x29, 0xdd, 0x58, 0x10, 0xea, 0x3f, 0x30, 0x0c, 0x4c, 0x48, 0x8d, 0x65, 0xa5, 0x27, 0x35, 0xb5,
	0xeb, 0x73, 0x16, 0x7e, 0x3d, 0xb2, 0x9d, 0x08, 0x0c, 0x13, 0xd3, 0xbb, 0xaf, 0xf7, 0xf4, 0xde,
	0xc1, 0x76, 0x6f, 0x51, 0xa8, 0xe3, 0x40, 0x5e, 0x3b, 0x61, 0x9d, 0xf1, 0x46, 0xd0, 0xd0, 0x92,
	0x72, 0x68, 0x3d, 0x9a, 0x13, 0xe5, 0x1d, 0x8f, 0x17, 0x6c, 0x91, 0x0d, 0x97, 0x2f, 0x1d, 0xfa,
	0xc3, 0xd0, 0x72, 0x65, 0x7a, 0x71, 0x68, 0x37, 0x9d, 0x11, 0x3d, 0x2a, 0x67, 0x36, 0xfd, 0x59,
	0xfc, 0x55, 0x57, 0x47, 0xd4, 0x27, 0x4f, 0x13, 0x26, 0xc5, 0xe5, 0xf3, 0x7f, 0x24, 0xbc, 0xb1,
	0xa8, 0x68, 0x84, 0x24, 0x50, 0x3f, 0xc1, 0xed, 0xeb, 0x4f, 0x53, 0x52, 0x9f, 0x19, 0x83, 0x4b,
	0xbb, 0xef, 0x74, 0x55, 0xac, 0x8a, 0xf5, 0x4c, 0xc6, 0x3a, 0xcc, 0x08, 0x3f, 0x75, 0x75, 0x91,
	0x66, 0xa1, 0xae, 0xdf, 0xe1, 0xee, 0x17, 0x97, 0x2c, 0xdb, 0x41, 0x9e, 0xb2, 0x2a, 0x56, 0xb3,
	0x75, 0xd9, 0xdc, 0xf3, 0xfc, 0x21, 0xdf, 0xc4, 0xd0, 0xcb, 0x9c, 0x53, 0x7f, 0xc0, 0x75, 0x7e,
	0xc0, 0x1e, 0x61, 0x9e, 0x92, 0x47, 0x57, 0x65, 0x73, 0xc3, 0xa7, 0x47, 0xec, 0x22, 0xca, 0x71,
	0xcd, 0x1e, 0xe0, 0x2a, 0x06, 0x8c, 0x4e, 0xcb, 0x66, 0xc1, 0xc7, 0xb8, 0x6f, 0x01, 0x64, 0xda,
	0xb5, 0xf3, 0x18, 0x7e, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x5b, 0x05, 0xea, 0xc6, 0x01,
	0x00, 0x00,
}
