# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

[app]
name = "Micro MQ"
access_key = "ak"
secret_key = "sk"

[server]
addr = "tcp://127.0.0.1:1883"
ws_addr = ":8080"

[auth]
# MockSuccess、MockFailure、rpc
provider = "MockSuccess"
addrs = ["127.0.0.1:8500"] # rpc服务发现

[broker]
# mock、kafka，默认mock
provider = "mock"
addrs = []

[sessions]
# mock、redis，默认mock
provider = "redis"

[database]
name = "db_name"
user_name = "user"
pwd  = "pwd"
host = "127.0.0.1"
port = "3306"

[redis]
server = "127.0.0.1:6379"
pwd = "123456"

[memcached]
server = "127.0.0.1:11211"

[opentracing]
disable = false

# jaeger or appdash
type = "jaeger"

# jaeger serviceName
service_name = "micro-mq"

# jaeger-agent 127.0.0.1:6831
# appdash http://localhost:8700
address = "127.0.0.1:6831"
