// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/client/proto/auth/auth.proto

/*
Package api_client_auth is a generated protocol buffer package.

It is generated from these files:
	api/client/proto/auth/auth.proto

It has these top-level messages:
	AuthReq
	AuthResp
*/
package api_client_auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Pwd  string `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
}

func (m *AuthReq) Reset()                    { *m = AuthReq{} }
func (m *AuthReq) String() string            { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()               {}
func (*AuthReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type AuthResp struct {
	Token    string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Verified bool   `protobuf:"varint,2,opt,name=verified" json:"verified,omitempty"`
}

func (m *AuthResp) Reset()                    { *m = AuthResp{} }
func (m *AuthResp) String() string            { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()               {}
func (*AuthResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResp) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func init() {
	proto.RegisterType((*AuthReq)(nil), "api_client_auth.AuthReq")
	proto.RegisterType((*AuthResp)(nil), "api_client_auth.AuthResp")
}

func init() { proto.RegisterFile("api/client/proto/auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x2c, 0xc8, 0xd4,
	0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0x2d,
	0xc9, 0x00, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x7f, 0x62, 0x41, 0x66, 0x3c, 0x44, 0x45, 0x3c, 0x48,
	0x58, 0x49, 0x9f, 0x8b, 0xdd, 0xb1, 0xb4, 0x24, 0x23, 0x28, 0xb5, 0x50, 0x48, 0x88, 0x8b, 0x25,
	0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe0, 0x62,
	0x2e, 0x28, 0x4f, 0x91, 0x60, 0x02, 0x0b, 0x81, 0x98, 0x4a, 0x36, 0x5c, 0x1c, 0x10, 0x0d, 0xc5,
	0x05, 0x42, 0x22, 0x5c, 0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x50, 0x2d, 0x10, 0x8e, 0x90, 0x14,
	0x17, 0x47, 0x59, 0x6a, 0x51, 0x66, 0x5a, 0x66, 0x2a, 0x44, 0x23, 0x47, 0x10, 0x9c, 0x9f, 0xc4,
	0x06, 0x76, 0x86, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xae, 0x33, 0x21, 0x99, 0xaa, 0x00, 0x00,
	0x00,
}
