// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cluster/proto/clients/clients.proto

/*
Package clients is a generated protocol buffer package.

It is generated from these files:
	api/cluster/proto/clients/clients.proto

It has these top-level messages:
	ClientsReq
	ClientsResp
	Client
*/
package clients

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import topics "github.com/hb-chen/micro-mq/api/cluster/proto/topics"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientsReq struct {
	Page int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *ClientsReq) Reset()                    { *m = ClientsReq{} }
func (m *ClientsReq) String() string            { return proto.CompactTextString(m) }
func (*ClientsReq) ProtoMessage()               {}
func (*ClientsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientsReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ClientsReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ClientsResp struct {
	Clients []*Client `protobuf:"bytes,1,rep,name=clients" json:"clients,omitempty"`
}

func (m *ClientsResp) Reset()                    { *m = ClientsResp{} }
func (m *ClientsResp) String() string            { return proto.CompactTextString(m) }
func (*ClientsResp) ProtoMessage()               {}
func (*ClientsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientsResp) GetClients() []*Client {
	if m != nil {
		return m.Clients
	}
	return nil
}

type Client struct {
	Id     string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Topics []*topics.Topic `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetTopics() []*topics.Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientsReq)(nil), "clients.ClientsReq")
	proto.RegisterType((*ClientsResp)(nil), "clients.ClientsResp")
	proto.RegisterType((*Client)(nil), "clients.Client")
}

func init() { proto.RegisterFile("api/cluster/proto/clients/clients.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xbf, 0x4a, 0xc5, 0x30,
	0x14, 0xc6, 0x69, 0xae, 0x54, 0x3c, 0x17, 0x15, 0x32, 0x05, 0xa7, 0x4b, 0x41, 0xac, 0x43, 0x13,
	0x50, 0x07, 0xb7, 0x0e, 0xbe, 0x41, 0xf0, 0x05, 0xda, 0x34, 0xb4, 0x07, 0x5a, 0x93, 0x36, 0xe9,
	0xe2, 0xd3, 0x4b, 0xf3, 0xc7, 0xe5, 0x4e, 0xdf, 0xc9, 0x77, 0x92, 0x5f, 0x7e, 0xf0, 0xd2, 0x59,
	0x14, 0x6a, 0xde, 0x9d, 0xd7, 0x9b, 0xb0, 0x9b, 0xf1, 0x46, 0xa8, 0x19, 0xf5, 0x8f, 0x77, 0x39,
	0x79, 0x68, 0xe9, 0x6d, 0x3a, 0x3e, 0xb5, 0x23, 0xfa, 0x69, 0xef, 0xb9, 0x32, 0x8b, 0x98, 0xfa,
	0x66, 0x34, 0x62, 0x41, 0xb5, 0x99, 0x66, 0x59, 0xc5, 0x35, 0xcb, 0x1b, 0x8b, 0xca, 0xa5, 0x88,
	0xa4, 0xea, 0x03, 0xe0, 0x2b, 0xb2, 0xa4, 0x5e, 0x29, 0x85, 0x1b, 0xdb, 0x8d, 0x9a, 0x15, 0x97,
	0xa2, 0x3e, 0xc9, 0x30, 0x1f, 0x9d, 0xc3, 0x5f, 0xcd, 0x48, 0xec, 0x8e, 0xb9, 0xfa, 0x84, 0xf3,
	0xff, 0x2b, 0x67, 0xe9, 0x2b, 0x64, 0x21, 0x56, 0x5c, 0x4e, 0xf5, 0xf9, 0xed, 0x91, 0x67, 0xdf,
	0x78, 0x4d, 0xe6, 0x7d, 0xd5, 0x42, 0x19, 0x2b, 0xfa, 0x00, 0x04, 0x87, 0xf0, 0xd3, 0x9d, 0x24,
	0x38, 0xd0, 0x67, 0x28, 0xa3, 0x19, 0x23, 0x81, 0x71, 0xcf, 0x93, 0xe8, 0xf7, 0x11, 0x32, 0x2d,
	0xfb, 0x32, 0x78, 0xbf, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x61, 0xc6, 0x49, 0x2c, 0x01,
	0x00, 0x00,
}
