// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/client/proto/define.proto

/*
Package api_client is a generated protocol buffer package.

It is generated from these files:
	api/client/proto/define.proto

It has these top-level messages:
*/
package api_client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SRV int32

const (
	SRV_client SRV = 0
)

var SRV_name = map[int32]string{
	0: "client",
}
var SRV_value = map[string]int32{
	"client": 0,
}

func (x SRV) String() string {
	return proto.EnumName(SRV_name, int32(x))
}
func (SRV) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type METHOD int32

const (
	METHOD_Auth     METHOD = 0
	METHOD_Register METHOD = 1
)

var METHOD_name = map[int32]string{
	0: "Auth",
	1: "Register",
}
var METHOD_value = map[string]int32{
	"Auth":     0,
	"Register": 1,
}

func (x METHOD) String() string {
	return proto.EnumName(METHOD_name, int32(x))
}
func (METHOD) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterEnum("api_client.SRV", SRV_name, SRV_value)
	proto.RegisterEnum("api_client.METHOD", METHOD_name, METHOD_value)
}

func init() { proto.RegisterFile("api/client/proto/define.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x49, 0x4d,
	0xcb, 0xcc, 0x4b, 0xd5, 0x03, 0x73, 0x84, 0xb8, 0x12, 0x0b, 0x32, 0xe3, 0x21, 0xd2, 0x5a, 0x82,
	0x5c, 0xcc, 0xc1, 0x41, 0x61, 0x42, 0x5c, 0x5c, 0x6c, 0x10, 0x01, 0x01, 0x06, 0x2d, 0x05, 0x2e,
	0x36, 0x5f, 0xd7, 0x10, 0x0f, 0x7f, 0x17, 0x21, 0x0e, 0x2e, 0x16, 0xc7, 0xd2, 0x92, 0x0c, 0x01,
	0x06, 0x21, 0x1e, 0x2e, 0x8e, 0xa0, 0xd4, 0xf4, 0xcc, 0xe2, 0x92, 0xd4, 0x22, 0x01, 0xc6, 0x24,
	0x36, 0xb0, 0x39, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x41, 0xda, 0x3b, 0x68, 0x00,
	0x00, 0x00,
}
