// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/proto/define.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	auth/proto/define.proto

It has these top-level messages:
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type BASE_PATH int32

const (
	BASE_PATH_rpc BASE_PATH = 0
)

var BASE_PATH_name = map[int32]string{
	0: "rpc",
}
var BASE_PATH_value = map[string]int32{
	"rpc": 0,
}

func (x BASE_PATH) String() string {
	return proto1.EnumName(BASE_PATH_name, int32(x))
}
func (BASE_PATH) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SRV int32

const (
	SRV_Auth SRV = 0
)

var SRV_name = map[int32]string{
	0: "Auth",
}
var SRV_value = map[string]int32{
	"Auth": 0,
}

func (x SRV) String() string {
	return proto1.EnumName(SRV_name, int32(x))
}
func (SRV) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type METHOD int32

const (
	METHOD_Verify METHOD = 0
)

var METHOD_name = map[int32]string{
	0: "Verify",
}
var METHOD_value = map[string]int32{
	"Verify": 0,
}

func (x METHOD) String() string {
	return proto1.EnumName(METHOD_name, int32(x))
}
func (METHOD) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterEnum("proto.BASE_PATH", BASE_PATH_name, BASE_PATH_value)
	proto1.RegisterEnum("proto.SRV", SRV_name, SRV_value)
	proto1.RegisterEnum("proto.METHOD", METHOD_name, METHOD_value)
}

func init() { proto1.RegisterFile("auth/proto/define.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x49, 0x4d, 0xcb, 0xcc, 0x4b, 0xd5, 0x03, 0x73,
	0x84, 0x58, 0xc1, 0x94, 0x96, 0x08, 0x17, 0xa7, 0x93, 0x63, 0xb0, 0x6b, 0x7c, 0x80, 0x63, 0x88,
	0x87, 0x10, 0x3b, 0x17, 0x73, 0x51, 0x41, 0xb2, 0x00, 0x83, 0x16, 0x3f, 0x17, 0x73, 0x70, 0x50,
	0x98, 0x10, 0x07, 0x17, 0x8b, 0x63, 0x69, 0x49, 0x86, 0x00, 0x83, 0x96, 0x08, 0x17, 0x9b, 0xaf,
	0x6b, 0x88, 0x87, 0xbf, 0x8b, 0x10, 0x17, 0x17, 0x5b, 0x58, 0x6a, 0x51, 0x66, 0x5a, 0xa5, 0x00,
	0x43, 0x12, 0x1b, 0xd8, 0x0c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0x20, 0x64, 0xb4,
	0x65, 0x00, 0x00, 0x00,
}
