// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cluster/proto/sessions/sessions.proto

/*
Package sessions is a generated protocol buffer package.

It is generated from these files:
	api/cluster/proto/sessions/sessions.proto

It has these top-level messages:
	SessionsReq
	SessionsResp
	Session
*/
package sessions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import topics "github.com/hb-go/micro-mq/api/cluster/proto/topics"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionsReq struct {
	Page int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *SessionsReq) Reset()                    { *m = SessionsReq{} }
func (m *SessionsReq) String() string            { return proto.CompactTextString(m) }
func (*SessionsReq) ProtoMessage()               {}
func (*SessionsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SessionsReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SessionsReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type SessionsResp struct {
	Sessions []*Session `protobuf:"bytes,1,rep,name=sessions" json:"sessions,omitempty"`
}

func (m *SessionsResp) Reset()                    { *m = SessionsResp{} }
func (m *SessionsResp) String() string            { return proto.CompactTextString(m) }
func (*SessionsResp) ProtoMessage()               {}
func (*SessionsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SessionsResp) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type Session struct {
	Id     string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Topics []*topics.Topic `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetTopics() []*topics.Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionsReq)(nil), "sessions.SessionsReq")
	proto.RegisterType((*SessionsResp)(nil), "sessions.SessionsResp")
	proto.RegisterType((*Session)(nil), "sessions.Session")
}

func init() { proto.RegisterFile("api/cluster/proto/sessions/sessions.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xc1, 0x4e, 0xc5, 0x20,
	0x10, 0x45, 0x53, 0x9e, 0x79, 0xea, 0x3c, 0x35, 0x91, 0x15, 0x71, 0xd5, 0x34, 0x31, 0xa9, 0x8b,
	0x42, 0xa2, 0x71, 0x69, 0xf4, 0x1b, 0xd0, 0x1f, 0x68, 0x29, 0x69, 0x27, 0xb1, 0x42, 0x3b, 0x74,
	0xe3, 0xd7, 0x9b, 0x52, 0xc4, 0x85, 0xab, 0xb9, 0x5c, 0x86, 0xc3, 0x81, 0x87, 0xd6, 0xa3, 0x32,
	0x9f, 0x2b, 0x05, 0xbb, 0x28, 0xbf, 0xb8, 0xe0, 0x14, 0x59, 0x22, 0x74, 0x5f, 0x94, 0x83, 0x8c,
	0x3d, 0xbf, 0xf8, 0x3d, 0xdf, 0xbd, 0x0e, 0x18, 0xc6, 0xb5, 0x93, 0xc6, 0x4d, 0x6a, 0xec, 0x9a,
	0xc1, 0xa9, 0x09, 0xcd, 0xe2, 0x9a, 0x69, 0x56, 0xff, 0x71, 0xc1, 0x79, 0x34, 0x94, 0xc6, 0x8e,
	0xaa, 0x9e, 0xe1, 0xf4, 0x9e, 0x60, 0xda, 0xce, 0x9c, 0xc3, 0x99, 0x6f, 0x07, 0x2b, 0x8a, 0xb2,
	0xa8, 0x0f, 0x3a, 0xe6, 0xad, 0x23, 0xfc, 0xb6, 0x82, 0xed, 0xdd, 0x96, 0xab, 0x17, 0xb8, 0xfa,
	0x7b, 0x46, 0x9e, 0x37, 0x90, 0x9d, 0x44, 0x51, 0x1e, 0xea, 0xd3, 0xe3, 0xad, 0xcc, 0xd2, 0x69,
	0x53, 0xe7, 0x95, 0xea, 0x0d, 0xce, 0x53, 0xc9, 0x6f, 0x80, 0x61, 0x1f, 0xff, 0xbb, 0xd4, 0x0c,
	0x7b, 0x7e, 0x0f, 0xc7, 0x5d, 0x50, 0xb0, 0xc8, 0xb9, 0x96, 0xc9, 0xf7, 0x63, 0x1b, 0x3a, 0x5d,
	0x76, 0xc7, 0xa8, 0xff, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0x83, 0x3c, 0xb9, 0x9c, 0x36, 0x01,
	0x00, 0x00,
}
