// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/client/proto/unregister/unregister.proto

/*
Package api_client_unregister is a generated protocol buffer package.

It is generated from these files:
	api/client/proto/unregister/unregister.proto

It has these top-level messages:
	UnregisterReq
	UnregisterResp
*/
package api_client_unregister

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UnregisterReq struct {
	ClientId string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty"`
}

func (m *UnregisterReq) Reset()                    { *m = UnregisterReq{} }
func (m *UnregisterReq) String() string            { return proto.CompactTextString(m) }
func (*UnregisterReq) ProtoMessage()               {}
func (*UnregisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UnregisterReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type UnregisterResp struct {
	ClientId string `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty"`
}

func (m *UnregisterResp) Reset()                    { *m = UnregisterResp{} }
func (m *UnregisterResp) String() string            { return proto.CompactTextString(m) }
func (*UnregisterResp) ProtoMessage()               {}
func (*UnregisterResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UnregisterResp) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func init() {
	proto.RegisterType((*UnregisterReq)(nil), "api_client_unregister.UnregisterReq")
	proto.RegisterType((*UnregisterResp)(nil), "api_client_unregister.UnregisterResp")
}

func init() { proto.RegisterFile("api/client/proto/unregister/unregister.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x49, 0x2c, 0xc8, 0xd4,
	0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xcd, 0x2b,
	0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0x42, 0x62, 0xea, 0x81, 0xe5, 0x84, 0x44, 0x13, 0x0b,
	0x32, 0xe3, 0x21, 0xaa, 0xe3, 0x11, 0x92, 0x4a, 0xda, 0x5c, 0xbc, 0xa1, 0x70, 0x5e, 0x50, 0x6a,
	0xa1, 0x90, 0x14, 0x17, 0x07, 0x44, 0x95, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x9c, 0xaf, 0xa4, 0xc3, 0xc5, 0x87, 0xac, 0xb8, 0xb8, 0x00, 0x9f, 0xea, 0x24, 0x36, 0xb0, 0xc5,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xf0, 0x99, 0x9d, 0xa8, 0x00, 0x00, 0x00,
}
