// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cluster/proto/define.proto

/*
Package cluster is a generated protocol buffer package.

It is generated from these files:
	api/cluster/proto/define.proto

It has these top-level messages:
*/
package cluster

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SRV int32

const (
	SRV_cluster SRV = 0
)

var SRV_name = map[int32]string{
	0: "cluster",
}
var SRV_value = map[string]int32{
	"cluster": 0,
}

func (x SRV) String() string {
	return proto.EnumName(SRV_name, int32(x))
}
func (SRV) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type METHOD int32

const (
	METHOD_Clients       METHOD = 0
	METHOD_Sessions      METHOD = 1
	METHOD_Subscriptions METHOD = 2
	METHOD_Topics        METHOD = 3
)

var METHOD_name = map[int32]string{
	0: "Clients",
	1: "Sessions",
	2: "Subscriptions",
	3: "Topics",
}
var METHOD_value = map[string]int32{
	"Clients":       0,
	"Sessions":      1,
	"Subscriptions": 2,
	"Topics":        3,
}

func (x METHOD) String() string {
	return proto.EnumName(METHOD_name, int32(x))
}
func (METHOD) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterEnum("cluster.SRV", SRV_name, SRV_value)
	proto.RegisterEnum("cluster.METHOD", METHOD_name, METHOD_value)
}

func init() { proto.RegisterFile("api/cluster/proto/define.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2c, 0xc8, 0xd4,
	0x4f, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x49,
	0x4d, 0xcb, 0xcc, 0x4b, 0xd5, 0x03, 0x73, 0x84, 0xd8, 0xa1, 0x72, 0x5a, 0x42, 0x5c, 0xcc, 0xc1,
	0x41, 0x61, 0x42, 0xdc, 0x5c, 0x30, 0x11, 0x01, 0x06, 0x2d, 0x27, 0x2e, 0x36, 0x5f, 0xd7, 0x10,
	0x0f, 0x7f, 0x17, 0x90, 0xb0, 0x73, 0x4e, 0x66, 0x6a, 0x5e, 0x49, 0xb1, 0x00, 0x83, 0x10, 0x0f,
	0x17, 0x47, 0x70, 0x6a, 0x71, 0x71, 0x66, 0x7e, 0x5e, 0xb1, 0x00, 0xa3, 0x90, 0x20, 0x17, 0x6f,
	0x70, 0x69, 0x52, 0x71, 0x72, 0x51, 0x66, 0x41, 0x09, 0x58, 0x88, 0x49, 0x88, 0x8b, 0x8b, 0x2d,
	0x24, 0xbf, 0x20, 0x33, 0xb9, 0x58, 0x80, 0x39, 0x89, 0x0d, 0x6c, 0x8f, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x4e, 0x77, 0x81, 0x5e, 0x89, 0x00, 0x00, 0x00,
}
