// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/cluster/proto/topics/topics.proto

/*
Package topics is a generated protocol buffer package.

It is generated from these files:
	api/cluster/proto/topics/topics.proto

It has these top-level messages:
	TopicsReq
	TopicsResp
	Topic
*/
package topics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopicsReq struct {
	Page int64 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
}

func (m *TopicsReq) Reset()                    { *m = TopicsReq{} }
func (m *TopicsReq) String() string            { return proto.CompactTextString(m) }
func (*TopicsReq) ProtoMessage()               {}
func (*TopicsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TopicsReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *TopicsReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type TopicsResp struct {
	Topics []*Topic `protobuf:"bytes,1,rep,name=topics" json:"topics,omitempty"`
}

func (m *TopicsResp) Reset()                    { *m = TopicsResp{} }
func (m *TopicsResp) String() string            { return proto.CompactTextString(m) }
func (*TopicsResp) ProtoMessage()               {}
func (*TopicsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TopicsResp) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type Topic struct {
	Topic string `protobuf:"bytes,1,opt,name=Topic" json:"Topic,omitempty"`
	Qos   int32  `protobuf:"varint,2,opt,name=Qos" json:"Qos,omitempty"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (m *Topic) String() string            { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Topic) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Topic) GetQos() int32 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func init() {
	proto.RegisterType((*TopicsReq)(nil), "topics.TopicsReq")
	proto.RegisterType((*TopicsResp)(nil), "topics.TopicsResp")
	proto.RegisterType((*Topic)(nil), "topics.Topic")
}

func init() { proto.RegisterFile("api/cluster/proto/topics/topics.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xc1, 0x0a, 0xc2, 0x30,
	0x0c, 0x40, 0x99, 0x75, 0x83, 0x45, 0x04, 0x29, 0x1e, 0x7a, 0x1c, 0x83, 0xc1, 0x4e, 0x2b, 0xd8,
	0x2f, 0xb1, 0xf8, 0x03, 0x73, 0x14, 0x29, 0x08, 0x8d, 0x4b, 0xbd, 0xf8, 0xf5, 0xd2, 0x2c, 0x3b,
	0xf5, 0xf5, 0xd1, 0xe6, 0x05, 0x86, 0x19, 0xa3, 0x5d, 0xde, 0x5f, 0xca, 0x61, 0xb5, 0xb8, 0xa6,
	0x9c, 0x6c, 0x4e, 0x18, 0x17, 0x92, 0x63, 0x62, 0xa7, 0x9b, 0xed, 0xd6, 0x3b, 0x68, 0x1f, 0x4c,
	0x3e, 0x7c, 0xb4, 0x86, 0x23, 0xce, 0xaf, 0x60, 0xaa, 0xae, 0x1a, 0x95, 0x67, 0x2e, 0x8e, 0xe2,
	0x2f, 0x98, 0xc3, 0xe6, 0x0a, 0xf7, 0x0e, 0x60, 0xff, 0x44, 0xa8, 0x07, 0x90, 0x61, 0xa6, 0xea,
	0xd4, 0x78, 0xba, 0x9d, 0x27, 0x29, 0xf1, 0x1b, 0xbf, 0x97, 0x2c, 0xd4, 0x2c, 0xf4, 0x55, 0x80,
	0x33, 0xad, 0x17, 0x7b, 0x01, 0x75, 0x4f, 0xc4, 0x99, 0xda, 0x17, 0x7c, 0x36, 0xbc, 0xa9, 0xfb,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x9a, 0xa6, 0xa2, 0xd2, 0x00, 0x00, 0x00,
}
